'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CarFront, ChevronRight, CircleDollarSign, Clock3, LayoutDashboard, LogOut, Menu, ShieldCheck, Smartphone, TrendingUp, UserCog, Users, Wallet, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { createVendor, getDashboard, getPortalRoles, getUserDetailById, getUsers, getVendors, getVisibleRoles, login, requestPasswordReset, resetPassword } from '@/lib/api';
import { DashboardSummary, Role, SortMode, UserDetail, UserSummary, Vendor } from '@/lib/types';

const INR = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 });
const dateTime = (v: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(v));

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="brand"><img src="/mpay-logo.png" alt="mPay"/><div><strong>mPay</strong>{!compact && <span>Admin Portal</span>}</div></div>;
}

export default function Page() {
  const [session, setSession] = useState<{token:string; refreshToken:string; role:Role; name:string; permissions:string[]} | null>(null);
  const [loginState, setLoginState] = useState<'login'|'forgot'>('login');
  const [portalRoles, setPortalRoles] = useState<string[]>(['ADMIN','MANAGER']);
  const [selectedPortalRole, setSelectedPortalRole] = useState('ADMIN');
  const [mobile, setMobile] = useState(''); const [password, setPassword] = useState(''); const [otp, setOtp] = useState(''); const [newPassword, setNewPassword] = useState('');
  const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [resetRequested, setResetRequested] = useState(false); const [view, setView] = useState<'dashboard'|'users'|'vendors'>('dashboard');
  const [dashboard, setDashboard] = useState<DashboardSummary>(); const [users, setUsers] = useState<UserSummary[]>([]); const [visibleUserRoles, setVisibleUserRoles] = useState<string[]>(['ADMIN','MANAGER','CLIENT']); const [vendors, setVendors] = useState<Vendor[]>([]);
  const [roleFilter, setRoleFilter] = useState<Role|'ALL'>('ALL'); const [sort, setSort] = useState<SortMode>('today-high'); const [selected, setSelected] = useState<UserDetail>(); const [drawer, setDrawer] = useState(false);
  const [newVendor, setNewVendor] = useState({ name:'', category:'CAR_RENT' as Vendor['category'], city:'', phone:'', commissionRate:5, active:true });

  useEffect(()=>{
    const raw = localStorage.getItem('mpay_admin_session');
    if(raw) setSession(JSON.parse(raw));
    getPortalRoles().then(roles=>{ if(roles.length) { setPortalRoles(roles); if(!roles.includes(selectedPortalRole)) setSelectedPortalRole(roles[0]); } }).catch(()=>{});
  },[]);

  useEffect(()=>{ if(session) { getDashboard().then(setDashboard); getVisibleRoles().then(setVisibleUserRoles).catch(()=>{}); loadUsers(); if(session.permissions?.includes('MANAGE_VENDORS')) getVendors().then(setVendors); } },[session]);
  async function loadUsers(){ setUsers(await getUsers(roleFilter, sort)); }
  useEffect(()=>{ if(session) loadUsers(); },[roleFilter, sort]);

  async function doLogin(e: React.FormEvent){ e.preventDefault(); setBusy(true); setNotice(''); try { const r = await login(mobile, password, selectedPortalRole); const s={token:r.accessToken, refreshToken:r.refreshToken, role:r.role, name:r.name||r.role, permissions:r.permissions||[]}; localStorage.setItem('mpay_admin_session', JSON.stringify(s)); localStorage.setItem('mpay_admin_token', r.accessToken); setSession(s); } catch(err:any){ setNotice(err.message||'Login failed'); } finally { setBusy(false); } }
  async function doReset(e: React.FormEvent){ e.preventDefault(); setBusy(true); try { if(!resetRequested){ await requestPasswordReset(mobile); setResetRequested(true); setNotice('OTP requested. Enter the OTP sent to the registered mobile number.'); } else { await resetPassword(mobile, otp, newPassword); setNotice('Password reset successful. You can now sign in.'); setLoginState('login'); setResetRequested(false); setOtp(''); setNewPassword(''); } } catch(err:any){ setNotice(err.message||'Reset failed'); } finally { setBusy(false); } }
  function logout(){ localStorage.removeItem('mpay_admin_session'); localStorage.removeItem('mpay_admin_token'); setSession(null); }

  if(!session) return <AuthScreen resetRequested={resetRequested} setResetRequested={setResetRequested} state={loginState} setState={setLoginState} mobile={mobile} setMobile={setMobile} password={password} setPassword={setPassword} otp={otp} setOtp={setOtp} newPassword={newPassword} setNewPassword={setNewPassword} busy={busy} notice={notice} onLogin={doLogin} onReset={doReset} portalRoles={portalRoles} selectedPortalRole={selectedPortalRole} setSelectedPortalRole={setSelectedPortalRole}/>;

  const permissions = session.permissions || [];
  const canVendors = permissions.includes('MANAGE_VENDORS');
  const menu = [
    ['dashboard','Dashboard',LayoutDashboard], ['users','Users',Users], ...(canVendors ? [['vendors','Vendors',CarFront] as const] : []),
  ] as const;

  return <div className="shell">
    <aside className={`sidebar ${drawer?'open':''}`}>
      <div className="side-top"><Logo compact/><button className="icon-btn mobile-only" onClick={()=>setDrawer(false)}><X size={19}/></button></div>
      <div className="portal-role"><ShieldCheck size={16}/><span>{session.role.replace('_',' ')} portal</span></div>
      <nav>{menu.map(([key,label,Icon])=><button key={key} className={view===key?'nav active':'nav'} onClick={()=>{setView(key as any);setDrawer(false)}}><Icon size={18}/><span>{label}</span></button>)}</nav>
      <div className="side-bottom"><div className="profile-mini"><div className="avatar">{session.name.charAt(0)}</div><div><b>{session.name}</b><span>{session.role}</span></div></div><button className="nav" onClick={logout}><LogOut size={18}/><span>Logout</span></button></div>
    </aside>
    <main className="main"><header className="topbar"><button className="icon-btn mobile-only" onClick={()=>setDrawer(true)}><Menu size={20}/></button><div><div className="eyebrow">mPay admin console</div><h1>{view==='dashboard'?'Company Overview':view==='users'?'Users':'Vendors & Services'}</h1></div><div className="top-actions"><span className="role-pill">{session.role}</span><button className="icon-btn"><UserCog size={18}/></button></div></header>
      {view==='dashboard' && <Dashboard data={dashboard} onUsers={()=>setView('users')} />}
      {view==='users' && <UsersView users={users} role={session.role} visibleRoles={visibleUserRoles} roleFilter={roleFilter} setRoleFilter={setRoleFilter} sort={sort} setSort={setSort} selected={selected} setSelected={setSelected}/>} 
      {view==='vendors' && canVendors && <VendorsView vendors={vendors} newVendor={newVendor} setNewVendor={setNewVendor} onAdd={async()=>{const v=await createVendor(newVendor);setVendors(x=>[v,...x]);setNewVendor({name:'',category:'CAR_RENT',city:'',phone:'',commissionRate:5,active:true});}}/>}
    </main>
  </div>
}

function AuthScreen(p:any){
  return <main className="auth-wrap"><div className="auth-card"><div className="auth-brand"><Logo/></div>{p.state==='login'?<><div className="auth-copy"><h1>Welcome to mPay Admin</h1><p>Sign in as Admin, Manager, or another enabled portal role.</p></div><form onSubmit={p.onLogin} className="form"><label>Portal role<select value={p.selectedPortalRole} onChange={e=>p.setSelectedPortalRole(e.target.value)}>{p.portalRoles.map((r:string)=><option key={r} value={r}>{r.charAt(0)+r.slice(1).toLowerCase()}</option>)}</select></label><label>Mobile number<input value={p.mobile} onChange={e=>p.setMobile(e.target.value)} placeholder="10-digit mobile number" /></label><label>Password<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} placeholder="Enter password" /></label>{p.notice&&<div className="alert">{p.notice}</div>}<button className="primary" disabled={p.busy}>{p.busy?'Signing in…':'Sign in'}</button><button type="button" className="link-btn" onClick={()=>{p.setState('forgot');p.notice&&p.setMobile(p.mobile)}}>Forgot password?</button></form></>:<><div className="auth-copy"><h1>Reset admin password</h1><p>Only Admin and Manager accounts can access this portal.</p></div><form onSubmit={p.onReset} className="form"><label>Registered mobile<input value={p.mobile} onChange={e=>p.setMobile(e.target.value)} placeholder="10-digit mobile number" /></label>{p.resetRequested&&<label>OTP<input value={p.otp} onChange={e=>p.setOtp(e.target.value)} placeholder="6-digit OTP" /></label>}{p.resetRequested&&<label>New password<input type="password" value={p.newPassword} onChange={e=>p.setNewPassword(e.target.value)} placeholder="New password" /></label>}{p.notice&&<div className="alert">{p.notice}</div>}<button className="primary" disabled={p.busy}>{p.busy?'Please wait…':p.resetRequested?'Reset password':'Send OTP'}</button><button type="button" className="link-btn" onClick={()=>{p.setState('login');p.setResetRequested(false)}}>Back to sign in</button></form></>}</div></main>
}

function Dashboard({data,onUsers}:{data?:DashboardSummary;onUsers:()=>void}){
  if(!data) return <div className="loading">Loading dashboard…</div>;
  const cards=[['Today earnings',data.todayCommission,'Commission earned today',CircleDollarSign],['Today volume',data.todayVolume,'Successful recharge value',Wallet],['This month',data.monthlyCommission,'Commission through today',TrendingUp],['Active clients',data.activeClients,'Currently active client accounts',Users]] as const;
  return <div className="content"><section className="metric-grid">{cards.map(([title,value,sub,Icon])=><div className="metric-card" key={title}><div className="metric-head"><span>{title}</span><div className="metric-icon"><Icon size={18}/></div></div><strong>{typeof value==='number'&&title!=='Active clients'?INR.format(value):value.toLocaleString('en-IN')}</strong><small>{sub}</small></div>)}</section><div className="split"><section className="panel"><div className="panel-head"><div><h2>Company performance</h2><p>Recharge volume and commission across the current period.</p></div><button className="secondary" onClick={onUsers}>View users <ChevronRight size={16}/></button></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.chart}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eee7dd"/><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip formatter={(v:any)=>INR.format(Number(v))}/><Bar dataKey="volume" fill="#f59e0b" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="panel"><div className="panel-head"><div><h2>Quick actions</h2><p>Common administration tasks.</p></div></div><div className="quick-grid"><button className="quick"><Users size={20}/><div><b>Manage users</b><span>View hierarchy, balances and earnings</span></div></button><button className="quick"><CarFront size={20}/><div><b>Manage vendors</b><span>Add car rental and service partners</span></div></button><button className="quick"><BarChart3 size={20}/><div><b>Commission rates</b><span>Review role-based earning rules</span></div></button><button className="quick"><Clock3 size={20}/><div><b>Audit activity</b><span>Review changes and operational events</span></div></button></div></section></div></div>
}

function UsersView({users,role,visibleRoles,roleFilter,setRoleFilter,sort,setSort,selected,setSelected}:{users:UserSummary[];role:Role;visibleRoles:string[];roleFilter:Role|'ALL';setRoleFilter:(v:any)=>void;sort:SortMode;setSort:(v:any)=>void;selected?:UserDetail;setSelected:(v:any)=>void}){
  const allowed = ['ALL', ...visibleRoles];
  return <div className="content"><section className="panel"><div className="panel-head wrap"><div><h2>User hierarchy</h2><p>{role==='ADMIN'?'Admins can see managers and clients. Managers can see clients only.':'You can see client accounts assigned under your management.'}</p></div><div className="filters"><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}>{allowed.map(r=><option key={r} value={r}>{r==='ALL'?'All users':r}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="today-high">Today: highest earnings</option><option value="today-low">Today: lowest earnings</option><option value="month-high">Month: highest earnings</option><option value="month-low">Month: lowest earnings</option></select></div></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Type</th><th>Today's earnings</th><th>Monthly earnings</th><th>Wallet</th><th>Status</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id} onClick={async()=>setSelected(await getUserDetailById(u.id))}><td><div className="user-cell"><div className="avatar light">{u.name.charAt(0)}</div><div><b>{u.name}</b><span>{u.mobile} · {u.publicUserId}</span></div></div></td><td><span className={`type-pill ${u.role.toLowerCase()}`}>{u.accountType}</span></td><td>{INR.format(u.todayEarnings)}</td><td>{INR.format(u.monthEarnings)}</td><td>{INR.format(u.walletBalance)}</td><td><span className={`status ${u.status.toLowerCase()}`}>{u.status}</span></td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div></section>{selected&&<UserDrawer user={selected} onClose={()=>setSelected(undefined)}/>}</div>
}

function UserDrawer({user,onClose}:{user:UserDetail;onClose:()=>void}){
  return <div className="drawer-overlay" onClick={onClose}><aside className="user-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">Account detail</div><h2>{user.name}</h2><span>{user.accountType} · {user.publicUserId}</span></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="detail-grid"><div><small>Mobile</small><b>{user.mobile}</b></div><div><small>Email</small><b>{user.email}</b></div><div><small>Wallet</small><b>{INR.format(user.walletBalance)}</b></div><div><small>Commission</small><b>{user.commissionRate}%</b></div><div><small>Today's earnings</small><b>{INR.format(user.todayEarnings)}</b></div><div><small>This month</small><b>{INR.format(user.monthEarnings)}</b></div></div><section className="drawer-section"><h3>Activity summary</h3><div className="summary-list"><span>Recharge count <b>{user.rechargeCount}</b></span><span>Add money <b>{INR.format(user.addMoneyTotal)}</b></span><span>Withdrawn <b>{INR.format(user.withdrawalTotal)}</b></span></div></section>{user.latestRecharge&&<section className="detail-card"><div className="detail-top"><span className="status success">SUCCESS</span><span>{dateTime(user.latestRecharge.createdAt)}</span></div><b>{user.latestRecharge.operator} · {user.latestRecharge.mobile}</b><div className="detail-row"><span>Recharge</span><strong>{INR.format(user.latestRecharge.amount)}</strong></div><div className="detail-row"><span>Commission</span><strong className="green">{INR.format(user.latestRecharge.commission)}</strong></div><div className="detail-row"><span>Transaction</span><strong>{user.latestRecharge.transactionId}</strong></div></section>}<div className="drawer-note">Admin and manager access is read-only for client wallets. This portal cannot recharge, add money, or withdraw on behalf of a user.</div></aside></div>
}

function VendorsView({vendors,newVendor,setNewVendor,onAdd}:{vendors:Vendor[];newVendor:any;setNewVendor:(v:any)=>void;onAdd:()=>void}){
  return <div className="content"><div className="split"><section className="panel"><div className="panel-head"><div><h2>Add vendor</h2><p>These partner services will later appear as quick actions for clients.</p></div></div><div className="form vendor-form"><label>Vendor name<input value={newVendor.name} onChange={e=>setNewVendor({...newVendor,name:e.target.value})}/></label><div className="two"><label>Category<select value={newVendor.category} onChange={e=>setNewVendor({...newVendor,category:e.target.value})}><option value="CAR_RENT">Car rental</option><option value="TRAVEL">Travel</option><option value="SERVICES">Other service</option></select></label><label>City<input value={newVendor.city} onChange={e=>setNewVendor({...newVendor,city:e.target.value})}/></label></div><label>Phone<input value={newVendor.phone} onChange={e=>setNewVendor({...newVendor,phone:e.target.value})}/></label><label>Commission %<input type="number" value={newVendor.commissionRate} onChange={e=>setNewVendor({...newVendor,commissionRate:Number(e.target.value)})}/></label><button className="primary" onClick={onAdd} disabled={!newVendor.name||!newVendor.city}>Add vendor</button></div></section><section className="panel"><div className="panel-head"><div><h2>Partner directory</h2><p>Active and inactive service vendors.</p></div></div><div className="vendor-list">{vendors.map(v=><div className="vendor-row" key={v.id}><div className="vendor-icon"><CarFront size={18}/></div><div className="vendor-main"><b>{v.name}</b><span>{v.category.replace('_',' ')} · {v.city} · {v.phone}</span></div><span className={`status ${v.active?'active':'blocked'}`}>{v.active?'ACTIVE':'INACTIVE'}</span></div>)}</div></section></div></div>
}
