'use client';
import { useEffect,useState } from 'react';
import { CheckCircle2,History,Home,LogOut,Menu,ReceiptText,Smartphone,UserRound,WalletCards,X,ArrowRight } from 'lucide-react';
const base=process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/,'')||'http://localhost:8080';
type Wallet={balance:number;availableBalance:number;reservedBalance:number};
type Me={name?:string;mobile:string;email?:string;role:string;publicUserId:string};
async function api(path:string,init?:RequestInit){const token=localStorage.getItem('mpay_token');const r=await fetch(base+path,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(init?.headers||{})}});if(!r.ok)throw new Error((await r.text())||'Request failed');return r.json();}
export default function Portal(){
 const [view,setView]=useState<'home'|'recharge'|'wallet'|'account'>('home'),[drawer,setDrawer]=useState(false),[wallet,setWallet]=useState<Wallet>(),[me,setMe]=useState<Me>(),[mobile,setMobile]=useState(''),[operator,setOperator]=useState<any>(),[plans,setPlans]=useState<any[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{if(!localStorage.getItem('mpay_token')){window.location.href='/login';return;}Promise.all([api('/api/v1/me'),api('/api/v1/wallet')]).then(([a,b])=>{setMe(a);setWallet(b)}).catch(()=>{localStorage.removeItem('mpay_token');window.location.href='/login'})},[]);
 function logout(){localStorage.removeItem('mpay_token');localStorage.removeItem('mpay_refresh_token');window.location.href='/';}
 async function detect(){setBusy(true);setNotice('');setPlans([]);try{const d=await api('/api/v1/recharge/operator',{method:'POST',body:JSON.stringify({mobileNumber:mobile})});setOperator(d);if(d.providerOperator&&d.circle){const q=await api('/api/v1/recharge/plans?mobile='+encodeURIComponent(mobile)+'&operator='+encodeURIComponent(d.operator)+'&circle='+encodeURIComponent(d.circle)+'&providerOperator='+encodeURIComponent(d.providerOperator)+'&providerCircle='+encodeURIComponent(d.providerCircle||''));setPlans(q?.plans||q||[])} }catch(e:any){setNotice(e.message||'Unable to detect operator or plans.')}finally{setBusy(false)}}
 const menu=[['home','Home',Home],['recharge','Recharge',Smartphone],['wallet','Wallet',WalletCards],['account','Account',UserRound]] as const;
 return <div className="portal-shell"><aside className={'portal-sidebar '+(drawer?'open':'')}><div className="portal-side-head"><a className="landing-brand" href="/"><img src="/mpay-logo.png" alt="mPay"/><span>mPay</span></a><button className="icon-btn mobile-only" onClick={()=>setDrawer(false)}><X size={18}/></button></div><div className="portal-welcome"><span>Signed in as</span><b>{me?.name||'mPay user'}</b><small>{me?.mobile||''}</small></div><nav>{menu.map(([key,label,Icon])=><button key={key} className={view===key?'portal-nav active':'portal-nav'} onClick={()=>{setView(key);setDrawer(false)}}><Icon size={18}/>{label}</button>)}</nav><button className="portal-nav portal-logout" onClick={logout}><LogOut size={18}/>Logout</button></aside><main className="portal-main"><header className="portal-topbar"><button className="icon-btn mobile-only" onClick={()=>setDrawer(true)}><Menu size={19}/></button><div><span>mPay personal workspace</span><h1>{view==='home'?'Good to see you.':view==='recharge'?'Mobile recharge':view==='wallet'?'Your wallet':'Your account'}</h1></div><div className="portal-avatar">{(me?.name||'U').charAt(0).toUpperCase()}</div></header>
 {view==='home'&&<section className="portal-content"><div className="portal-hero-card"><div><span>AVAILABLE TO SPEND</span><strong>₹{Number(wallet?.availableBalance||0).toLocaleString('en-IN',{minimumFractionDigits:2})}</strong><p>Keep an eye on available and reserved funds before your next payment.</p></div><button className="landing-primary" onClick={()=>setView('recharge')}>Recharge now <ArrowRight size={16}/></button></div><div className="portal-card-grid"><button onClick={()=>setView('recharge')}><Smartphone/><b>Mobile recharge</b><span>Choose a plan and continue to payment.</span></button><button onClick={()=>setView('wallet')}><WalletCards/><b>Wallet</b><span>View balance, available funds and history.</span></button><button onClick={()=>setView('account')}><UserRound/><b>Account</b><span>Review your profile and account details.</span></button></div></section>}
 {view==='wallet'&&<section className="portal-content"><div className="wallet-grid"><div className="wallet-big"><span>Total balance</span><strong>₹{Number(wallet?.balance||0).toLocaleString('en-IN',{minimumFractionDigits:2})}</strong></div><div><span>Available</span><b>₹{Number(wallet?.availableBalance||0).toLocaleString('en-IN',{minimumFractionDigits:2})}</b></div><div><span>Reserved</span><b>₹{Number(wallet?.reservedBalance||0).toLocaleString('en-IN',{minimumFractionDigits:2})}</b></div></div><div className="portal-panel"><h2>Wallet activity</h2><p>Every balance movement is recorded by the same wallet ledger used by mPay.</p><button className="landing-secondary" onClick={()=>setView('home')}><History size={16}/> Back to home</button></div></section>}
 {view==='account'&&<section className="portal-content"><div className="portal-panel account-panel"><div className="account-large-avatar">{(me?.name||'U').charAt(0).toUpperCase()}</div><h2>{me?.name||'mPay user'}</h2><p>{me?.publicUserId}</p><div className="account-facts"><div><span>Mobile</span><b>{me?.mobile}</b></div><div><span>Email</span><b>{me?.email||'Not provided'}</b></div><div><span>Account type</span><b>{me?.role||'CLIENT'}</b></div></div></div></section>}
 {view==='recharge'&&<section className="portal-content"><div className="portal-panel"><div className="panel-head"><div><h2>Recharge a mobile</h2><p>Enter a number to detect the operator and load available plans.</p></div></div><div className="recharge-web-form"><input inputMode="numeric" maxLength={10} value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,''))} placeholder="10-digit mobile number"/><button className="primary" disabled={busy||mobile.length!==10} onClick={detect}>{busy?'Checking…':'Find plans'}</button></div>{notice&&<div className="alert">{notice}</div>}{operator&&<div className="operator-result"><CheckCircle2 size={18}/><div><b>{operator.operator}</b><span>{operator.circle} · {operator.type||'Mobile'}</span></div></div>}{plans.length>0&&<div className="web-plan-grid">{plans.map((p:any)=><div className="web-plan" key={p.id||p.amount}><div><strong>₹{Number(p.amount).toLocaleString('en-IN')}</strong><span>{p.validity||'Plan'}</span></div><p>{p.description||'Recharge plan'}</p><button className="landing-secondary">Continue <ArrowRight size={14}/></button></div>)}</div>}{operator&&!plans.length&&!busy&&<div className="empty-state">No plans were returned for this number.</div>}</div></section>}
 </main></div>
}