import Link from "next/link";
import { ArrowLeft, ArrowRight, CalendarDays, ChevronRight, Heart, MapPin, Search, ShoppingBag, Stethoscope, Utensils, BriefcaseBusiness } from "lucide-react";
import StoreShell from "../../../../StoreShell";
import { websites } from "../../../../data";
export function generateStaticParams(){return websites.flatMap(w=>w.pages.slice(1).map(p=>({slug:w.slug,path:[p.toLowerCase().replaceAll(" ","-")]})));}
function DemoBody({w,path}:{w:any;path:string[]}){const route=path[0]||""; const isHome=!route; const c=w.theme;
 const hero = c==="luma" ? {k:"LUMA DINING",t:"Tables worth remembering.",s:"Seasonal plates, warm rooms, slow evenings.",icon:<Utensils/>}:{};
 if(c==="estate") return <div className="demo-site demo-estate"><div className="demo-nav"><b>ESTATE ONE</b><span>Properties</span><span>Agents</span><span>About</span><button>Enquire</button></div>{isHome||route==="properties"?<><div className="demo-wide-hero"><small>PROPERTY COLLECTION 2026</small><h1>Find a place that feels<br/>like yours.</h1><div className="demo-search"><Search size={16}/><span>City, neighbourhood or postcode</span><button>Search</button></div></div><div className="demo-cards">{["The Oak Residence","Riverline House","Palm Court"].map((x,i)=><article key={x}><div className="property-art" data-i={i}/><small>3 BED · {i+2} BATH</small><h3>{x}</h3><span>₹{(1.4+i*.35).toFixed(2)} Cr · New Delhi</span></article>)}</div></>:<div className="demo-page-block"><small>PROPERTY DETAIL</small><h1>{route.replaceAll("-"," ")}</h1><p>Immersive listing layout with imagery, amenities, agent details and an enquiry path.</p><button>Request details</button></div>}</div>;
 if(c==="novacare") return <div className="demo-site demo-clinic"><div className="demo-nav"><b>NOVACARE</b><span>Services</span><span>Doctors</span><span>About</span><button>Book appointment</button></div>{isHome||route==="doctors"?<><div className="clinic-hero"><div><small>CARE, WITHOUT THE WAIT.</small><h1>Feel better.<br/>Move forward.</h1><p>Thoughtful care, experienced doctors and appointments designed around your day.</p><button>Find a doctor</button></div><div className="clinic-art"><Stethoscope size={52}/></div></div><div className="doctor-row">{["Dr. Mira Rao","Dr. Anil Shah","Dr. Neha Sen"].map(x=><article key={x}><div className="avatar-art">{x.slice(4,5)}</div><b>{x}</b><span>Internal Medicine</span><button>View profile</button></article>)}</div></>:<div className="demo-page-block"><small>APPOINTMENTS</small><h1>Choose a time that works.</h1><div className="slot-grid">{["09:30","11:00","14:30","17:00"].map(s=><button key={s}>{s}</button>)}</div><button>Continue</button></div>}</div>;
 if(c==="vertex") return <div className="demo-site demo-vertex"><div className="demo-nav dark"><b>VERTEX</b><span>Services</span><span>Case studies</span><span>Insights</span><button>Let's talk</button></div><div className="vertex-hero"><small>STRATEGY / PRODUCT / GROWTH</small><h1>Clarity for the<br/><em>next chapter.</em></h1><p>We help ambitious teams make difficult decisions feel simple.</p><button>Explore our work</button></div><div className="vertex-stats"><div><b>42</b><span>launches</span></div><div><b>18</b><span>markets</span></div><div><b>9.4/10</b><span>client signal</span></div></div></div>;
 if(c==="atelier") return <div className="demo-site demo-atelier"><div className="demo-nav"><b>ATELIER</b><span>New in</span><span>Collections</span><span>Journal</span><button><ShoppingBag size={16}/> Bag · 0</button></div>{isHome||route==="shop"?<><div className="atelier-hero"><small>AW26 · STUDIO COLLECTION</small><h1>Made for the<br/>in-between.</h1><button>Shop collection <ArrowRight size={15}/></button></div><div className="product-row">{["Axis coat","Form knit","Line tote","Studio shoe"].map((x,i)=><article key={x}><div className="fashion-art" data-i={i}/><small>ATELIER / {String(i+1).padStart(2,"0")}</small><b>{x}</b><span>₹{(7.9+i*1.1).toFixed(1)}k</span><button><Heart size={14}/> Save</button></article>)}</div></>:<div className="demo-page-block"><small>PRODUCT DETAIL</small><h1>{route.replaceAll("-"," ")}</h1><p>Variant selector, gallery, sizing and add-to-bag flow are ready for productisation.</p><button>Add to bag</button></div>}</div>;
 return <div className="demo-site demo-luma"><div className="demo-nav"><b>LUMA</b><span>Menu</span><span>About</span><span>Gallery</span><button>Reserve</button></div>{isHome||route==="menu"?<><div className="luma-hero"><div><small>{hero.k}</small><h1>{hero.t}</h1><p>{hero.s}</p><button>Reserve a table</button></div><div className="luma-art"><div className="plate"/><div className="wine"/>{hero.icon}</div></div><div className="luma-menu"><span>TONIGHT AT LUMA</span><div><b>Charred cauliflower</b><em>₹680</em></div><div><b>Truffle ravioli</b><em>₹1,120</em></div><div><b>Burnt honey tart</b><em>₹540</em></div></div></>:<div className="demo-page-block"><small>{route.toUpperCase()}</small><h1>An intentional page, built to convert.</h1><p>Hero content, editorial imagery, structured information and a clear action area complete this route.</p><button>Continue</button></div>}</div>;
}
export default async function DemoPage({params}:{params:Promise<{slug:string;path?:string[]}>}){const p=await params;const w=websites.find(x=>x.slug===p.slug)??websites[0];return <StoreShell><main className={`demo-shell ${w.theme}`}><div className="demo-topbar"><Link href={`/websites/${w.slug}`}><ArrowLeft size={15}/> Exit demo</Link><span>{w.name} · live demo</span><Link href="/websites">All websites <ArrowRight size={15}/></Link></div><DemoBody w={w} path={p.path??[]}/></main></StoreShell>}
